// Refresh deliberately; normal builds use the reviewed, pinned schema.
import { createHash } from 'node:crypto';
import { readFile, writeFile, mkdir } from 'node:fs/promises';

const source = 'https://cad.onshape.com/api/openapi';
const bytes = process.argv[2] ? await readFile(process.argv[2]) : Buffer.from(await (await fetch(source)).arrayBuffer());
const spec = JSON.parse(bytes);
if (!spec.openapi?.startsWith('3.') || !spec.paths || !spec.components?.schemas) throw new Error('Expected Onshape OpenAPI 3 schema');
const operations = Object.entries(spec.paths).flatMap(([path, item]) => Object.entries(item)
  .filter(([method]) => ['get', 'post', 'put', 'patch', 'delete', 'head', 'options', 'trace'].includes(method))
  .map(([method, operation]) => {
    if (!operation.operationId) throw new Error(`Missing operation ID: ${method} ${path}`);
    return { id: operation.operationId, method: method.toUpperCase(), path };
  })).sort((a, b) => a.id.localeCompare(b.id, 'en'));
if (new Set(operations.map(o => o.id)).size !== operations.length) throw new Error('Duplicate operation IDs');
// JSON strings are valid Haskell string literals for these ASCII identifiers and paths.
const quote = value => { if (!/^[\x20-\x7e]*$/.test(value)) throw new Error('Non-ASCII identifier'); return JSON.stringify(value); };
const generated = `{-# LANGUAGE OverloadedStrings #-}
-- Generated by scripts/import-onshape.mjs. Do not edit by hand.
module Zither.Operations (Operation(..), operations, apiBase) where
import Data.Text (Text)
data Operation = Operation { operationId :: Text, method :: Text, path :: Text } deriving (Eq, Show)
apiBase :: Text
apiBase = ${quote(spec.servers[0].url)}
operations :: [Operation]
operations =
  [ ${operations.map(o => `Operation ${quote(o.id)} ${quote(o.method)} ${quote(o.path)}`).join('\n  , ')}
  ]
`;
await mkdir('kernel/schema', { recursive: true });
await writeFile('kernel/schema/onshape-openapi.json', bytes);
await writeFile('kernel/schema/source.json', JSON.stringify({ source, version: spec.info.version, apiBase: spec.servers[0].url,
  sha256: createHash('sha256').update(bytes).digest('hex'), operations: operations.length, schemas: Object.keys(spec.components.schemas).length }, null, 2) + '\n');
await writeFile('kernel/src/Zither/Operations.hs', generated);
console.log(`Imported ${operations.length} operations and ${Object.keys(spec.components.schemas).length} schemas.`);
